### PR TITLE
More flexible defaults

### PR DESCRIPTION
**Pull request by brettz9**
Provide more flexible defaults:

1. Smoothly handle omitted initial whitespace by returning empty string when not present
2. If line number missing, parse as line 0
3. Insist on at least one character in `file://` URL

### CODE REVIEW

**Comment by jdlehman** [comment]
Looks good for the most part. I am wondering if it is a bit misleading to show missing line numbers as 0. Maybe we should show something else to indicate it didn't find 0 in actuality?

**Comment by brettz9** [comment]
Yes, sure. I just wanted to call out the issue, so let me know what you'd like in its place and I can modify/rebase. (And if there's no real concern about whether this would even occur, an alternative might be changing `\d*` to `\d+`.) 

Consumers could always override anyhow but I just thought it could be tightened up a little though it was secondary to my more immediate concern of no initial whitespace (as was the case in a stream I'm working with).

I'm also intending to submit a PR to allow overriding or enhancing `getRawSourceMap` to be able to conditionally load URLs instead of files as I have a case where the application is dynamically generating the file with no desktop file to read from.  If you have any thoughts about how you might like to see that take shape, let me know.

**Comment by jdlehman** [comment]
I like the idea of changing `\d*` to `\d+` for the default regex.

As far as `getRawSourceMap` goes, I think that enhancement sounds awesome.

Maybe using a regex to check if it is a url and then splitting the logic into two methods for getting the file depending on if it is local or remote.

```js
export function getRawSourceMap(path) {
  var fileData = isUrl(path) ? getRemoteFile(path): getLocalFile(path);
  // rest of logic
}
```

**Comment by jdlehman** [comment]
Once you make the change to the regex for `\d+` can you rebuild the `dist` files too and we can get this merged?

**Comment by brettz9** [comment]
I'll take a look, but I think I like your approach for `getRawSourceMap`, especially if we can override those as necessary (e.g., I have some URLs which are expressed without a protocol so my app would need to be responsible for determining whether it was a URL or not).

Ok for me to change to `const`/`let` over `var`, btw?

Are you ok with me adding https://github.com/feross/eslint-config-standard to enforce a common ESLint style?

Though I don't have plans to add them myself, if you ever get to adding unit tests, I'd be happy to ensure we stay covered.

**Comment by brettz9** [comment]
Also, as Node doesn't seem to have any synchronous HTTP tools out of the box, just wanted to confirm it's ok to refactor to load asynchronously (we're in a stream anyways)...

**Comment by jdlehman** [comment]
Async load is 👍 by me. 

Also same for `const`/`let`. I was actually thinking of that one myself as I tend to prefer `const` and `let` over `var` these days (I guess I didn't back when I wrote this)

**Comment by jdlehman** [comment]
Oh and the standard eslint is fine by me. I generally tend to prefer semicolons, but I think as long as the project is consistent I am fine with whatever.

**Comment by brettz9** [comment]
Great... I overrode the semi-colons rule to require them--the default without them is just wrong :) . I've seen other projects override it too. Besides requiring `const`/`let`, I added a tighter rule to `prefer-const` (over `let`) when the variable is not redefined anywhere in code. I find these rules to be very helpful.

**Pull request merged**
